/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ijlblffpxiuwvpmjorlo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqbGJsZmZweGl1d3ZwbWpvcmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4MDk3MjgsImV4cCI6MjEwNDM4NTcyOH0.eppHqas_emX0t_Mrtth8ickrKHcdyStK-8LHd2Q3V-4"